/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wangzhe.util;

import javax.script.Invocable;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;

/**
 *
 * @author ocq
 */
public class JavaScriptUtil {

    public String invokeScriptMethod(String password, String miyao, String verifycode) {
        ScriptEngineManager sem = new ScriptEngineManager();
        ScriptEngine se = sem.getEngineByName("javascript");
        String callbackvalue = null;
        try {

            Invocable invocableEngine = (Invocable) se;
//		
            // 调用有参数JAVASCRIPT函数
            se.eval("var hexcase = 1;\n"
                    + "var b64pad = \"\";\n"
                    + "var chrsz = 8;\n"
                    + "var mode = 32;\n"
                    + "function md5(A) {\n"
                    + "	return hex_md5(A)\n"
                    + "}\n"
                    + "function hex_md5(A) {\n"
                    + "	return binl2hex(core_md5(str2binl(A), A.length * chrsz))\n"
                    + "}\n"
                    + "function str_md5(A) {\n"
                    + "	return binl2str(core_md5(str2binl(A), A.length * chrsz))\n"
                    + "}\n"
                    + "function hex_hmac_md5(A, B) {\n"
                    + "	return binl2hex(core_hmac_md5(A, B))\n"
                    + "}\n"
                    + "function b64_hmac_md5(A, B) {\n"
                    + "	return binl2b64(core_hmac_md5(A, B))\n"
                    + "}\n"
                    + "function str_hmac_md5(A, B) {\n"
                    + "	return binl2str(core_hmac_md5(A, B))\n"
                    + "}\n"
                    + "function core_md5(K, F) {\n"
                    + "	K[F >> 5] |= 128 << ((F) % 32);\n"
                    + "	K[(((F + 64) >>> 9) << 4) + 14] = F;\n"
                    + "	var J = 1732584193;\n"
                    + "	var I = -271733879;\n"
                    + "	var H = -1732584194;\n"
                    + "	var G = 271733878;\n"
                    + "	for ( var C = 0; C < K.length; C += 16) {\n"
                    + "		var E = J;\n"
                    + "		var D = I;\n"
                    + "		var B = H;\n"
                    + "		var A = G;\n"
                    + "		J = md5_ff(J, I, H, G, K[C + 0], 7, -680876936);\n"
                    + "		G = md5_ff(G, J, I, H, K[C + 1], 12, -389564586);\n"
                    + "		H = md5_ff(H, G, J, I, K[C + 2], 17, 606105819);\n"
                    + "		I = md5_ff(I, H, G, J, K[C + 3], 22, -1044525330);\n"
                    + "		J = md5_ff(J, I, H, G, K[C + 4], 7, -176418897);\n"
                    + "		G = md5_ff(G, J, I, H, K[C + 5], 12, 1200080426);\n"
                    + "		H = md5_ff(H, G, J, I, K[C + 6], 17, -1473231341);\n"
                    + "		I = md5_ff(I, H, G, J, K[C + 7], 22, -45705983);\n"
                    + "		J = md5_ff(J, I, H, G, K[C + 8], 7, 1770035416);\n"
                    + "		G = md5_ff(G, J, I, H, K[C + 9], 12, -1958414417);\n"
                    + "		H = md5_ff(H, G, J, I, K[C + 10], 17, -42063);\n"
                    + "		I = md5_ff(I, H, G, J, K[C + 11], 22, -1990404162);\n"
                    + "		J = md5_ff(J, I, H, G, K[C + 12], 7, 1804603682);\n"
                    + "		G = md5_ff(G, J, I, H, K[C + 13], 12, -40341101);\n"
                    + "		H = md5_ff(H, G, J, I, K[C + 14], 17, -1502002290);\n"
                    + "		I = md5_ff(I, H, G, J, K[C + 15], 22, 1236535329);\n"
                    + "		J = md5_gg(J, I, H, G, K[C + 1], 5, -165796510);\n"
                    + "		G = md5_gg(G, J, I, H, K[C + 6], 9, -1069501632);\n"
                    + "		H = md5_gg(H, G, J, I, K[C + 11], 14, 643717713);\n"
                    + "		I = md5_gg(I, H, G, J, K[C + 0], 20, -373897302);\n"
                    + "		J = md5_gg(J, I, H, G, K[C + 5], 5, -701558691);\n"
                    + "		G = md5_gg(G, J, I, H, K[C + 10], 9, 38016083);\n"
                    + "		H = md5_gg(H, G, J, I, K[C + 15], 14, -660478335);\n"
                    + "		I = md5_gg(I, H, G, J, K[C + 4], 20, -405537848);\n"
                    + "		J = md5_gg(J, I, H, G, K[C + 9], 5, 568446438);\n"
                    + "		G = md5_gg(G, J, I, H, K[C + 14], 9, -1019803690);\n"
                    + "		H = md5_gg(H, G, J, I, K[C + 3], 14, -187363961);\n"
                    + "		I = md5_gg(I, H, G, J, K[C + 8], 20, 1163531501);\n"
                    + "		J = md5_gg(J, I, H, G, K[C + 13], 5, -1444681467);\n"
                    + "		G = md5_gg(G, J, I, H, K[C + 2], 9, -51403784);\n"
                    + "		H = md5_gg(H, G, J, I, K[C + 7], 14, 1735328473);\n"
                    + "		I = md5_gg(I, H, G, J, K[C + 12], 20, -1926607734);\n"
                    + "		J = md5_hh(J, I, H, G, K[C + 5], 4, -378558);\n"
                    + "		G = md5_hh(G, J, I, H, K[C + 8], 11, -2022574463);\n"
                    + "		H = md5_hh(H, G, J, I, K[C + 11], 16, 1839030562);\n"
                    + "		I = md5_hh(I, H, G, J, K[C + 14], 23, -35309556);\n"
                    + "		J = md5_hh(J, I, H, G, K[C + 1], 4, -1530992060);\n"
                    + "		G = md5_hh(G, J, I, H, K[C + 4], 11, 1272893353);\n"
                    + "		H = md5_hh(H, G, J, I, K[C + 7], 16, -155497632);\n"
                    + "		I = md5_hh(I, H, G, J, K[C + 10], 23, -1094730640);\n"
                    + "		J = md5_hh(J, I, H, G, K[C + 13], 4, 681279174);\n"
                    + "		G = md5_hh(G, J, I, H, K[C + 0], 11, -358537222);\n"
                    + "		H = md5_hh(H, G, J, I, K[C + 3], 16, -722521979);\n"
                    + "		I = md5_hh(I, H, G, J, K[C + 6], 23, 76029189);\n"
                    + "		J = md5_hh(J, I, H, G, K[C + 9], 4, -640364487);\n"
                    + "		G = md5_hh(G, J, I, H, K[C + 12], 11, -421815835);\n"
                    + "		H = md5_hh(H, G, J, I, K[C + 15], 16, 530742520);\n"
                    + "		I = md5_hh(I, H, G, J, K[C + 2], 23, -995338651);\n"
                    + "		J = md5_ii(J, I, H, G, K[C + 0], 6, -198630844);\n"
                    + "		G = md5_ii(G, J, I, H, K[C + 7], 10, 1126891415);\n"
                    + "		H = md5_ii(H, G, J, I, K[C + 14], 15, -1416354905);\n"
                    + "		I = md5_ii(I, H, G, J, K[C + 5], 21, -57434055);\n"
                    + "		J = md5_ii(J, I, H, G, K[C + 12], 6, 1700485571);\n"
                    + "		G = md5_ii(G, J, I, H, K[C + 3], 10, -1894986606);\n"
                    + "		H = md5_ii(H, G, J, I, K[C + 10], 15, -1051523);\n"
                    + "		I = md5_ii(I, H, G, J, K[C + 1], 21, -2054922799);\n"
                    + "		J = md5_ii(J, I, H, G, K[C + 8], 6, 1873313359);\n"
                    + "		G = md5_ii(G, J, I, H, K[C + 15], 10, -30611744);\n"
                    + "		H = md5_ii(H, G, J, I, K[C + 6], 15, -1560198380);\n"
                    + "		I = md5_ii(I, H, G, J, K[C + 13], 21, 1309151649);\n"
                    + "		J = md5_ii(J, I, H, G, K[C + 4], 6, -145523070);\n"
                    + "		G = md5_ii(G, J, I, H, K[C + 11], 10, -1120210379);\n"
                    + "		H = md5_ii(H, G, J, I, K[C + 2], 15, 718787259);\n"
                    + "		I = md5_ii(I, H, G, J, K[C + 9], 21, -343485551);\n"
                    + "		J = safe_add(J, E);\n"
                    + "		I = safe_add(I, D);\n"
                    + "		H = safe_add(H, B);\n"
                    + "		G = safe_add(G, A)\n"
                    + "	}\n"
                    + "	if (mode == 16) {\n"
                    + "		return Array(I, H)\n"
                    + "	} else {\n"
                    + "		return Array(J, I, H, G)\n"
                    + "	}\n"
                    + "}\n"
                    + "function md5_cmn(F, C, B, A, E, D) {\n"
                    + "	return safe_add(bit_rol(safe_add(safe_add(C, F), safe_add(A, D)), E), B)\n"
                    + "}\n"
                    + "function md5_ff(C, B, G, F, A, E, D) {\n"
                    + "	return md5_cmn((B & G) | ((~B) & F), C, B, A, E, D)\n"
                    + "}\n"
                    + "function md5_gg(C, B, G, F, A, E, D) {\n"
                    + "	return md5_cmn((B & F) | (G & (~F)), C, B, A, E, D)\n"
                    + "}\n"
                    + "function md5_hh(C, B, G, F, A, E, D) {\n"
                    + "	return md5_cmn(B ^ G ^ F, C, B, A, E, D)\n"
                    + "}\n"
                    + "function md5_ii(C, B, G, F, A, E, D) {\n"
                    + "	return md5_cmn(G ^ (B | (~F)), C, B, A, E, D)\n"
                    + "}\n"
                    + "function core_hmac_md5(C, F) {\n"
                    + "	var E = str2binl(C);\n"
                    + "	if (E.length > 16) {\n"
                    + "		E = core_md5(E, C.length * chrsz)\n"
                    + "	}\n"
                    + "	var A = Array(16), D = Array(16);\n"
                    + "	for ( var B = 0; B < 16; B++) {\n"
                    + "		A[B] = E[B] ^ 909522486;\n"
                    + "		D[B] = E[B] ^ 1549556828\n"
                    + "	}\n"
                    + "	var G = core_md5(A.concat(str2binl(F)), 512 + F.length * chrsz);\n"
                    + "	return core_md5(D.concat(G), 512 + 128)\n"
                    + "}\n"
                    + "function safe_add(A, D) {\n"
                    + "	var C = (A & 65535) + (D & 65535);\n"
                    + "	var B = (A >> 16) + (D >> 16) + (C >> 16);\n"
                    + "	return (B << 16) | (C & 65535)\n"
                    + "}\n"
                    + "function bit_rol(A, B) {\n"
                    + "	return (A << B) | (A >>> (32 - B))\n"
                    + "}\n"
                    + "function str2binl(D) {\n"
                    + "	var C = Array();\n"
                    + "	var A = (1 << chrsz) - 1;\n"
                    + "	for ( var B = 0; B < D.length * chrsz; B += chrsz) {\n"
                    + "		C[B >> 5] |= (D.charCodeAt(B / chrsz) & A) << (B % 32)\n"
                    + "	}\n"
                    + "	return C\n"
                    + "}\n"
                    + "function binl2str(C) {\n"
                    + "	var D = \"\";\n"
                    + "	var A = (1 << chrsz) - 1;\n"
                    + "	for ( var B = 0; B < C.length * 32; B += chrsz) {\n"
                    + "		D += String.fromCharCode((C[B >> 5] >>> (B % 32)) & A)\n"
                    + "	}\n"
                    + "	return D\n"
                    + "}\n"
                    + "function binl2hex(C) {\n"
                    + "	var B = hexcase ? \"0123456789ABCDEF\" : \"0123456789abcdef\";\n"
                    + "	var D = \"\";\n"
                    + "	for ( var A = 0; A < C.length * 4; A++) {\n"
                    + "		D += B.charAt((C[A >> 2] >> ((A % 4) * 8 + 4)) & 15)\n"
                    + "				+ B.charAt((C[A >> 2] >> ((A % 4) * 8)) & 15)\n"
                    + "	}\n"
                    + "	return D\n"
                    + "}\n"
                    + "function binl2b64(D) {\n"
                    + "	var C = \"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\";\n"
                    + "	var F = \"\";\n"
                    + "	for ( var B = 0; B < D.length * 4; B += 3) {\n"
                    + "		var E = (((D[B >> 2] >> 8 * (B % 4)) & 255) << 16)\n"
                    + "				| (((D[B + 1 >> 2] >> 8 * ((B + 1) % 4)) & 255) << 8)\n"
                    + "				| ((D[B + 2 >> 2] >> 8 * ((B + 2) % 4)) & 255);\n"
                    + "		for ( var A = 0; A < 4; A++) {\n"
                    + "			if (B * 8 + A * 6 > D.length * 32) {\n"
                    + "				F += b64pad\n"
                    + "			} else {\n"
                    + "				F += C.charAt((E >> 6 * (3 - A)) & 63)\n"
                    + "			}\n"
                    + "		}\n"
                    + "	}\n"
                    + "	return F\n"
                    + "}\n"
                    + "function hexchar2bin(str) {\n"
                    + "	var arr = [];\n"
                    + "	for ( var i = 0; i < str.length; i = i + 2) {\n"
                    + "		arr.push(\"\\\\x\" + str.substr(i, 2))\n"
                    + "	}\n"
                    + "	arr = arr.join(\"\");\n"
                    + "	eval(\"var temp = '\" + arr + \"'\");\n"
                    + "	return temp\n"
                    + "}\n"
                    + "function uin2hex(str) {\n"
                    + "	var maxLength = 16;\n"
                    + "	str = parseInt(str);\n"
                    + "	var hex = str.toString(16);\n"
                    + "	var len = hex.length;\n"
                    + "	for ( var i = len; i < maxLength; i++) {\n"
                    + "		hex = \"0\" + hex\n"
                    + "	}\n"
                    + "	var arr = [];\n"
                    + "	for ( var j = 0; j < maxLength; j += 2) {\n"
                    + "		arr.push(\"\\\\x\" + hex.substr(j, 2))\n"
                    + "	}\n"
                    + "	var result = arr.join(\"\");\n"
                    + "	eval('result=\"' + result + '\"');\n"
                    + "	return result\n"
                    + "}\n"
                    + "\n"
                    + "//加密\n"
                    + "function passwordEncoding(password, code2, verifycode) {\n"
                    + "	var I =  hexchar2bin(md5(password));\n"
                    + "	var H = md5(I + code2);\n"
                    + "	var G = md5(H + verifycode);\n"
                    + "	\n"
                    + "	return G;\n"
                    + "}");

            callbackvalue = (String) invocableEngine.invokeFunction("passwordEncoding", password, miyao, verifycode);
            System.out.println(callbackvalue);

        } catch (ScriptException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (NoSuchMethodException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        return callbackvalue;

    }
}
